from pathlib import Path
class OperationError(Exception): ...
class NativeContent:
    @staticmethod
    def text(value: str) -> NativeContent: ...
    @staticmethod
    def html(value: str) -> NativeContent: ...
    @staticmethod
    def sequence(values: list[NativeContent]) -> NativeContent: ...
class NativeMedia:
    @staticmethod
    def file(path: str, max_bytes: int) -> NativeMedia: ...
    @staticmethod
    def bytes(data: bytes, media_type: str, max_bytes: int) -> NativeMedia: ...
    def with_export_name(self, name: str) -> NativeMedia: ...
    def filename(self) -> str: ...
    def media_type(self) -> str: ...
    def size(self) -> int: ...
    def image(self) -> NativeContent: ...
    def sound(self) -> NativeContent: ...
class NativeNoteType:
    @staticmethod
    def build(input: str, assets: list[NativeMedia]) -> NativeNoteType: ...
    @staticmethod
    def from_bundle(path: str, max_bytes: int) -> NativeNoteType: ...
    def key(self) -> str: ...
    def display_name(self) -> str: ...
    def note(self) -> NativeNote: ...
class NativeNote:
    @staticmethod
    def basic(front: NativeContent, back: NativeContent) -> NativeNote: ...
    @staticmethod
    def cloze(text: NativeContent) -> NativeNote: ...
    @staticmethod
    def image_occlusion(image: NativeMedia, masks: list[tuple[str, float, float, float, float]], mode: str) -> NativeNote: ...
    def field(self, key: str, value: NativeContent) -> NativeNote: ...
    def deck(self, name: str) -> NativeNote: ...
    def tags(self, tags: list[str]) -> NativeNote: ...
    def note_type(self) -> NativeNoteType: ...
class NativeProject:
    def __init__(self, namespace: str, name: str | None = ..., default_deck: str | None = ...) -> None: ...
    def add(self, key: str, note: NativeNote) -> None: ...
    def add_asset(self, media: NativeMedia) -> None: ...
    def len(self) -> int: ...
    def build(self, input: str) -> tuple[str, NativeArtifact]: ...
    def compare(self, input: str) -> str: ...
class NativeArtifact:
    def clone_handle(self) -> NativeArtifact: ...
    def persist_to(self, path: str) -> NativeArtifact: ...
    def path(self) -> Path: ...
    def close(self) -> None: ...
def binding_metadata() -> str: ...
def validate_risk_code(code: str) -> None: ...
