from os import PathLike
from pathlib import Path

class OperationError(Exception): ...

class NativeArtifact:
    def path(self) -> Path: ...
    def close(self) -> None: ...

class NativeMediaRef:
    @property
    def filename(self) -> str: ...

class NativeProject:
    def __init__(self, name: str, stable_id: str | None = None, default_deck: str | None = None) -> None: ...
    def add_note(self, note: str, references: list[NativeMediaRef]) -> None: ...
    def add_media_file(self, path: str | PathLike[str], export_as: str) -> NativeMediaRef: ...
    def build(self, output: str | PathLike[str] | None = None) -> tuple[str, NativeArtifact | None]: ...

def binding_metadata() -> str: ...
