from os import PathLike
from pathlib import Path

class OperationError(Exception): ...

class NativeArtifact:
    def path(self) -> Path: ...
    def close(self) -> None: ...
    def clone_handle(self) -> NativeArtifact: ...
    def persist_to(self, path: str | PathLike[str]) -> NativeArtifact: ...

class NativeMediaRef:
    @property
    def filename(self) -> str: ...

class NativeProject:
    def __init__(self, name: str, stable_id: str | None = None, default_deck: str | None = None) -> None: ...
    def add_note(self, note: str, references: list[NativeMediaRef]) -> None: ...
    def add_notetype(self, note_type: str) -> None: ...
    def validate(self) -> str: ...
    def notes(self) -> str: ...
    def notetypes(self) -> str: ...
    def add_media_file(self, path: str | PathLike[str], export_as: str) -> NativeMediaRef: ...
    def add_media_bytes(self, source_label: str, data: bytes, export_as: str) -> NativeMediaRef: ...
    def build(self, options: str) -> tuple[str, NativeArtifact | None]: ...

def binding_metadata() -> str: ...
def default_field_key(name: str) -> str: ...
def default_template_key(name: str) -> str: ...
def render_content(content: str, references: list[NativeMediaRef]) -> str: ...
def build_image_occlusion(input: str, image: NativeMediaRef) -> str: ...
def inline_media_limit_bytes() -> int: ...
def default_inspect_limits() -> str: ...
